development:
  adapter: postgresql
  database: xml_stats_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: xml_stats_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: xml_stats
  pool: 5
  timeout: 5000
